#!/usr/bin/env bun
// ── TypeGen CLI ──
// Reads the collection schema from a Boltstore server and generates TypeScript
// type definitions (.d.ts) for all collections.
//
// Usage: boltstore typegen [options]

import { parseArgs } from "node:util";
import type { CollectionSchema, FieldSchema, FieldType } from "@boltstore/shared";

// ── Type Mapping ──

const TYPE_MAP: Record<FieldType, string> = {
  text: "string",
  email: "string",
  url: "string",
  select: "string",
  number: "number",
  bool: "boolean",
  date: "string",
  json: "Record<string, unknown>",
  file: "string",
  relation: "string",
};

// ── Code Generation ──

function fieldToTypeScript(field: FieldSchema): string {
  const baseType = TYPE_MAP[field.type] ?? "unknown";
  const optional = field.required ? "" : "?";
  const docs = `/** ${field.type}${field.required ? " (required)" : ""} */`;

  return `  ${docs}\n  ${field.name}${optional}: ${baseType};`;
}

function collectionToTypeScript(collection: CollectionSchema): string {
  const pascalName = toPascalCase(collection.name);

  const fields = collection.fields
    .map(fieldToTypeScript)
    .join("\n");

  return `
export interface ${pascalName} {
  id: string;
  collectionId: string;
  collectionName: string;
${fields}
  created: string;
  updated: string;
}
`.trim();
}

function toPascalCase(str: string): string {
  return str
    .split(/[_-]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

// ── Schema Fetching ──

async function fetchSchemas(url: string, apiKey?: string): Promise<CollectionSchema[]> {
  const headers: Record<string, string> = {};
  if (apiKey) {
    headers["Authorization"] = apiKey.startsWith("bs_") ? apiKey : `Bearer ${apiKey}`;
  }

  const response = await fetch(`${url}/api/collections`, { headers });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Failed to fetch schemas: ${response.status} ${text}`);
  }

  const result = await response.json();
  if (!result.success) {
    throw new Error(result.error?.message ?? "Failed to fetch schemas");
  }

  return result.data ?? [];
}

// ── CLI ──

async function main(): Promise<void> {
  const { values, positionals } = parseArgs({
    args: Bun.argv.slice(2),
    options: {
      url: { type: "string", default: "http://localhost:8090" },
      output: { type: "string", default: "boltstore.d.ts" },
      apiKey: { type: "string" },
      help: { type: "boolean", short: "h" },
    },
    strict: false,
    allowPositionals: true,
  });

  if (values.help) {
    console.log(`
Boltstore TypeGen — Generate TypeScript types from your schema

Usage:
  boltstore typegen [options]

Options:
  --url <url>       Boltstore server URL (default: http://localhost:8090)
  --output <file>   Output .d.ts file (default: boltstore.d.ts)
  --api-key <key>   API key or JWT token for authentication
  --help, -h        Show this help
`);
    return;
  }

  console.log(`📡 Fetching schema from ${values.url}...`);

  try {
    const collections = await fetchSchemas(values.url!, values.apiKey);

    if (collections.length === 0) {
      console.log("⚠️  No collections found. Create some collections first.");
      return;
    }

    // Generate type definitions
    const header = `// Auto-generated by Boltstore TypeGen
// Source: ${values.url}
// Generated: ${new Date().toISOString()}
// Collections: ${collections.map((c) => c.name).join(", ")}

// Re-export from @boltstore/shared for convenience
import type { RecordData, PaginatedResponse, ApiResponse } from "@boltstore/shared";

`;

    const types = collections.map(collectionToTypeScript).join("\n\n");

    const footer = `
// ── Convenience type for all records ──
export type BoltstoreRecord = ${collections.map((c) => toPascalCase(c.name)).join(" | ")};

// ── Record map by collection name ──
export interface BoltstoreSchema {
${collections.map((c) => `  "${c.name}": ${toPascalCase(c.name)};`).join("\n")}
}
`;

    const output = header + types + footer;

    await Bun.write(values.output!, output);
    console.log(`✅ Generated ${collections.length} types → ${values.output}`);
  } catch (err) {
    console.error(`❌ ${err instanceof Error ? err.message : err}`);
    process.exit(1);
  }
}

main();
